# 한국투자증권 API 설정
# 실제 값은 .env 파일에서 관리합니다.
# 환경변수를 사용하지 않을 경우 아래 기본값이 사용됩니다.

# 거래 모드 설정
# 'simulation' 또는 'real'
# 환경변수 TRADE_MODE로 오버라이드 가능
trade_mode: simulation

# 모의투자 계좌 (환경변수로 오버라이드됨)
simulation:
  api_key: ${SIMULATION_API_KEY}
  secret_key: ${SIMULATION_SECRET_KEY}
  account_id: ${SIMULATION_ACCOUNT_ID}
  htsid: ${SIMULATION_HTSID}

# 실거래 계좌 (환경변수로 오버라이드됨)
real:
  api_key: ${REAL_API_KEY}
  secret_key: ${REAL_SECRET_KEY}
  account_id: ${REAL_ACCOUNT_ID}
  htsid: ${REAL_HTSID}
